//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexos
    {
        public int id { get; set; }
        public int opcionMaestroAnexoId { get; set; }
        public Nullable<int> registroTablaId { get; set; }
        public int usuarioId { get; set; }
        public byte[] anexo { get; set; }
        public string nombreAnexo { get; set; }
        public string consecutivoTemporal { get; set; }
    
        public virtual OpcionesMaestroAnexos OpcionesMaestroAnexos { get; set; }
    }
}
