//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUsuarios.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroAnexos
    {
        public MaestroAnexos()
        {
            this.OpcionesMaestroAnexos = new HashSet<OpcionesMaestroAnexos>();
            this.ConsecutivosTemporales = new HashSet<ConsecutivosTemporales>();
        }
    
        public int id { get; set; }
        public string tabla { get; set; }
        public int usuarioId { get; set; }
        public int aplicacionId { get; set; }
    
        public virtual ICollection<OpcionesMaestroAnexos> OpcionesMaestroAnexos { get; set; }
        public virtual ICollection<ConsecutivosTemporales> ConsecutivosTemporales { get; set; }
        public virtual AplicacionesWeb AplicacionesWeb { get; set; }
    }
}
